name: Python

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Format
        run: |
          python -m pip install --upgrade pip
          pip install black
          black . --check --diff --color

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Lint
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          flake8 . --statistics
